#############################################
OutputDirPath:
  #'/wsu/tmp/YasukiAAPaper/MATTER_LBT_RunningAlphaS_Q2qhat_3D'
  #'/wsu/tmp/YasukiAAPaper/MATTER_LBT_RunningAlphaS'  
  '/wsu/tmp/YasukiRHIC'  

CodePath:
  '/wsu/home/go/go54/go5410/YasukiRHICWorkingDir/JETSCAPE'
  #'/Users/yasukitachibana/GoogleDrive/Codes/JETSCAPE'


#############################################
OriginalUserXml:
  AA:
    'config/jetscape_user_pbpb_sample.xml'  
    #'config/jetscape_user_no_br_test.xml'
    #'config/jetscape_user_br_test.xml'
    #'config/jetscape_user_pbpb_grid.xml'
    #'config/jetscape_user.xml'
  PP:
    'config/jetscape_user_PP19.xml'
MasterXml:
    #'config/jetscape_master.xml'
    'config/jetscape_main.xml' #For JETSCAPE 3.5.2
#############################################
HydroType: 
  #[["hydro_type", 4], ["boost_invariant_", 0]] #for 3D
  {} #for 2D

HydroFilePath:
  5020:
    #'/wsu/home/groups/maj-shen/JETSCAPEDataFile/HydroProfiles/3DHydro_5TeV_{}' #3D
    '/wsu/home/groups/maj-shen/JETSCAPEDataFile/HydroProfiles/5020GeV_{}' #2D
  2760:
    '/wsu/home/groups/maj-shen/JETSCAPEDataFile/HydroProfiles/2760GeV-{}'
  200:
    '/wsu/home/groups/maj-shen/JETSCAPEDataFile/HydroProfiles/200GeV_{}'
#############################################
Notification:
  OnOff: 1
  Email: 'yasuki.tachibana@gmail.com'
  Merge: 0
#############################################
MergedFileDirPath:
  '/wsu/tmp/YasukiAAPaper/MATTER_LBT_RunningAlphaS'
#############################################
QueOptions:
  ' --time=200:00:00 -N 1 -n 1 --mem=8G '
#############################################
qhat: 5
  #0Fixed
  #1Run
  #5Q2
t_start: '0.6'
temp_f: '0.16'
#############################################
JLoss:
  ['Matter','LBT']
MatterBroadening: 0
#############################################
run: 
  [0,60]
RandomRandomSeed: 
  0
#############################################

nEvents: 
  4000 #for 2D  
nReuseHydro: #2000 # for 3D (> nEvents)
  20 #for 2D 
  #10 #for 2D 5TeV 0-10


#############################################
CMakeOption: ''
MakeOption: ''
#############################################
pthat:
  PGun:
    5020: [[100], [120], [140], [160], [180], [200], [250], [300], [350], [400], [450], [500], [1000], [1500] ]
    2760: [[100], [120], [140], [160], [180], [200], [250], [300], [350], [400], [450], [500] ]
    200: [[10], [15], [20], [25], [30], [35], [40], [45], [50], [60], [80], [100] ]

  PythiaGun:
    5020:
      [
        [2400, 2510],
        [2200, 2400],
        [2000, 2200],
        [1900, 2000],
        [1800, 1900],
        [1700, 1800],
        [1600, 1700],
        [1500, 1600],
        [1400, 1500],
        [1300, 1400],
        [1200, 1300],
        [1100, 1200],
        [1000, 1100],
        [900, 1000],
        [800, 900],
        [700, 800],
        [600, 700],
        [550, 600],
        [500, 550],
        [450, 500],
        [400, 450],
        [350, 400],
        [300, 350],
        [290, 300],
        [280, 290],
        [270, 280],
        [260, 270],
        [250, 260],
        [240, 250],
        [230, 240],
        [220, 230],
        [210, 220],
        [200, 210],
        [190, 200],
        [180, 190],
        [170, 180],
        [160, 170],
        [150, 160],
        [140, 150],
        [130, 140],
        [120, 130],
        [110, 120],
        [100, 110],
        [90, 100],
        [80, 90],
        [70, 80],
        [60, 70],
        [55, 60],
        [50, 55],
        [45, 50],
        [40, 45],
        [35, 40],
        [30, 35],
        [25, 30],
        [20, 25],
        [17, 20],
        [15, 17],
        [13, 15],
        [11, 13],
        [9, 11],
        [7, 9],
        [5, 7],
        [4, 5],
        [3, 4],
        [2, 3],
        [1, 2],
      ]
    2760:
      [
        [1300, 1380],
        [1200, 1300],
        [1100, 1200],
        [1000, 1100],
        [900, 1000],
        [800, 900],
        [700, 800],
        [600, 700],
        [550, 600],
        [500, 550],
        [450, 500],
        [400, 450],
        [350, 400],
        [300, 350],
        [290, 300],
        [280, 290],
        [270, 280],
        [260, 270],
        [250, 260],
        [240, 250],
        [230, 240],
        [220, 230],
        [210, 220],
        [200, 210],
        [190, 200],
        [180, 190],
        [170, 180],
        [160, 170],
        [150, 160],
        [140, 150],
        [130, 140],
        [120, 130],
        [110, 120],
        [100, 110],
        [90, 100],
        [80, 90],
        [70, 80],
        [60, 70],
        [55, 60],
        [50, 55],
        [45, 50],
        [40, 45],
        [35, 40],
        [30, 35],
        [25, 30],
        [20, 25],
        [17, 20],
        [15, 17],
        [13, 15],
        [11, 13],
        [9, 11],
        [7, 9],
        [5, 7],
        [4, 5],
        [3, 4],
        [2, 3],
        [1, 2],
      ]
    200:
      [
        [90, 100],
        [80, 90],
        [70, 80],
        [60, 70],
        [55, 60],
        [50, 55],
        [45, 50],
        [40, 45],
        [35, 40],
        [30, 35],
        [25, 30],
        [20, 25],
        [17, 20],
        [15, 17],
        [13, 15],
        [11, 13],
        [9, 11],
        [7, 9],
        [5, 7],
        [4, 5],
        [3, 4],
        [2, 3],
        [1, 2],
      ]